# Generated by Django 4.2.7 on 2023-11-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="pedido", table="pedidos",),
    ]
