# Generated by Django 4.2.7 on 2023-11-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_alter_pedido_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineapedido", old_name="combo_id", new_name="combo",
        ),
        migrations.RenameField(
            model_name="lineapedido", old_name="pedido_id", new_name="pedido",
        ),
    ]
