# Generated by Django 4.2.7 on 2023-11-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peticion", "0004_alter_lineapeticion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="lineapeticion", table="lineapeticion",),
        migrations.AlterModelTable(name="peticion", table="peticiones",),
    ]
