# Generated by Django 4.2.7 on 2023-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_producto_created_producto_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="Componente",
            options={
                "verbose_name": "componente",
                "verbose_name_plural": "componentes",
            },
        ),
        migrations.RenameField(
            model_name="componente", old_name="categorias", new_name="categoria",
        ),
        migrations.RenameModel(old_name="Producto", new_name="Componente",),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("componentes", models.ManyToManyField(to="menu.componente")),
            ],
            options={"verbose_name": "combo", "verbose_name_plural": "combos",},
        ),
    ]
